language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install:
  - yarn
script:
  - yarn test
  - yarn lint
  - yarn build
